FROM tazihad/byedpi:v0.17.3

LABEL net.kasefuchs.build.image="byedpi"
LABEL net.kasefuchs.build.platforms="linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le"

# Install curl for health checks.
RUN apk --no-cache add curl
