# Copyright (c) Kasefuchs
# SPDX-License-Identifier: MIT

FROM tazihad/byedpi:v0.17.2

LABEL su.kasefuchs.build.platforms="linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le"

# Install curl for health checks.
RUN apk --no-cache add curl
